/*
 * Copyright (c) 2019 Sprint
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdio.h>
#include <string.h>

#include "fd.h"

#include "gx.h"

GxDict gxDict;

int gxInit(void)
{
    int rval = FD_REASON_OK;
    vendor_id_t vnd_etsi = 13019;
    vendor_id_t vnd_3gpp2 = 5535;
    vendor_id_t vnd_3gpp = 10415;

    application_id_t app_gx = 16777238;

    TRC2(gxInit);

    memset(&gxDict, 0, sizeof(gxDict));

    /* lookup ETSI Vendor */
    FDCHECK_FCT_DICT(DICT_VENDOR, VENDOR_BY_ID, &vnd_etsi, gxDict.vndETSI, rval, goto err);
    /* lookup 3GPP2 Vendor */
    FDCHECK_FCT_DICT(DICT_VENDOR, VENDOR_BY_ID, &vnd_3gpp2, gxDict.vnd3GPP2, rval, goto err);
    /* lookup 3GPP Vendor */
    FDCHECK_FCT_DICT(DICT_VENDOR, VENDOR_BY_ID, &vnd_3gpp, gxDict.vnd3GPP, rval, goto err);

    /* lookup GX application */
    FDCHECK_FCT_DICT(DICT_APPLICATION, APPLICATION_BY_ID, &app_gx, gxDict.appGX, rval, goto err);


	//FDCHECK_FCT_DICT_GETVAL(gxDict.appGX, &gxDict.davp_appGX, rval, goto err);
	//FDCHECK_FCT_DICT_GETVAL(gxDict.vnd3GPP, &gxDict.davp_vnd3GPP, rval, goto err);
	//FDCHECK_FCT_DICT_GETVAL(gxDict.vnd3GPP2, &gxDict.davp_vnd3GPP2, rval, goto err);
	//FDCHECK_FCT_DICT_GETVAL(gxDict.vndETSI, &gxDict.davp_vndETSI, rval, goto err);

    /* lookup commands */
    FDCHECK_FCT_DICT(DICT_COMMAND, CMD_BY_NAME, "Re-Auth-Request", gxDict.cmdRAR, rval, goto err);
    FDCHECK_FCT_DICT(DICT_COMMAND, CMD_BY_NAME, "Re-Auth-Answer", gxDict.cmdRAA, rval, goto err);
    FDCHECK_FCT_DICT(DICT_COMMAND, CMD_BY_NAME, "Credit-Control-Answer", gxDict.cmdCCA, rval, goto err);
    FDCHECK_FCT_DICT(DICT_COMMAND, CMD_BY_NAME, "Credit-Control-Request", gxDict.cmdCCR, rval, goto err);

    /* lookup AVPs */
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TDF-Destination-Host", gxDict.avp_tdf_destination_host, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Pre-emption-Capability", gxDict.avp_pre_emption_capability, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Packet-Filter-Content", gxDict.avp_packet_filter_content, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Feature-List-ID", gxDict.avp_feature_list_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Resource-Release-Notification", gxDict.avp_resource_release_notification, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Service-Identifier", gxDict.avp_service_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Physical-Access-Id", gxDict.avp_physical_access_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "CSG-Access-Mode", gxDict.avp_csg_access_mode, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "HeNB-Local-IP-Address", gxDict.avp_henb_local_ip_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Dynamic-Address-Flag-Extension", gxDict.avp_dynamic_address_flag_extension, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "APN-Aggregate-Max-Bitrate-UL", gxDict.avp_apn_aggregate_max_bitrate_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Network-Request-Support", gxDict.avp_network_request_support, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Termination-Cause", gxDict.avp_termination_cause, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Exponent", gxDict.avp_exponent, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-RAT-Type", gxDict.avp_3gpp_rat_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "AF-Signalling-Protocol", gxDict.avp_af_signalling_protocol, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Packet-Filter-Usage", gxDict.avp_packet_filter_usage, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Usage-Monitoring-Support", gxDict.avp_usage_monitoring_support, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Tracking-Area-Identity", gxDict.avp_tracking_area_identity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Load-Value", gxDict.avp_load_value, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Feature-List", gxDict.avp_feature_list, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "OMC-Id", gxDict.avp_omc_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "RAI", gxDict.avp_rai, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "OC-Report-Type", gxDict.avp_oc_report_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Experimental-Result", gxDict.avp_experimental_result, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Service-Context-Id", gxDict.avp_service_context_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Request-Type", gxDict.avp_cc_request_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Secondary-Event-Charging-Function-Name", gxDict.avp_secondary_event_charging_function_name, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "PCSCF-Restoration-Indication", gxDict.avp_pcscf_restoration_indication, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TDF-IP-Address", gxDict.avp_tdf_ip_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Load-Type", gxDict.avp_load_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Extended-GBR-DL", gxDict.avp_extended_gbr_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "OC-Feature-Vector", gxDict.avp_oc_feature_vector, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Origin-Host", gxDict.avp_origin_host, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "PRA-Remove", gxDict.avp_pra_remove, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Maximum-Wait-Time", gxDict.avp_maximum_wait_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "List-Of-Measurements", gxDict.avp_list_of_measurements, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "QoS-Information", gxDict.avp_qos_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Final-Unit-Action", gxDict.avp_final_unit_action, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Conditional-Policy-Information", gxDict.avp_conditional_policy_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "DRMP", gxDict.avp_drmp, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "PRA-Install", gxDict.avp_pra_install, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Logical-Access-Id", gxDict.avp_logical_access_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Resource-Allocation-Notification", gxDict.avp_resource_allocation_notification, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Rule-Deactivation-Time", gxDict.avp_rule_deactivation_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Flow-Status", gxDict.avp_flow_status, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Priority-Level", gxDict.avp_priority_level, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Pre-emption-Vulnerability", gxDict.avp_pre_emption_vulnerability, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Bearer-Usage", gxDict.avp_bearer_usage, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Reporting-Reason", gxDict.avp_reporting_reason, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "QoS-Class-Identifier", gxDict.avp_qos_class_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-SGSN-MCC-MNC", gxDict.avp_3gpp_sgsn_mcc_mnc, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Area-Scope", gxDict.avp_area_scope, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Re-Auth-Request-Type", gxDict.avp_re_auth_request_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Precedence", gxDict.avp_precedence, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Flow-Number", gxDict.avp_flow_number, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "PDN-Connection-Charging-ID", gxDict.avp_pdn_connection_charging_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-PS-Data-Off-Status", gxDict.avp_3gpp_ps_data_off_status, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Redirect-Host-Usage", gxDict.avp_redirect_host_usage, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "AN-GW-Address", gxDict.avp_an_gw_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Tunnel-Header-Filter", gxDict.avp_tunnel_header_filter, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Access-Network-Charging-Identifier-Value", gxDict.avp_access_network_charging_identifier_value, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Secondary-Charging-Collection-Function-Name", gxDict.avp_secondary_charging_collection_function_name, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TCP-Source-Port", gxDict.avp_tcp_source_port, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Destination-Host", gxDict.avp_destination_host, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-Selection-Mode", gxDict.avp_3gpp_selection_mode, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Location-Area-Identity", gxDict.avp_location_area_identity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Logging-Interval", gxDict.avp_logging_interval, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Flow-Information", gxDict.avp_flow_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "UE-Local-IP-Address", gxDict.avp_ue_local_ip_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Extended-APN-AMBR-DL", gxDict.avp_extended_apn_ambr_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TDF-Application-Identifier", gxDict.avp_tdf_application_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Tunnel-Information", gxDict.avp_tunnel_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Media-Component-Status", gxDict.avp_media_component_status, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TFT-Packet-Filter-Information", gxDict.avp_tft_packet_filter_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Guaranteed-Bitrate-UL", gxDict.avp_guaranteed_bitrate_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Online", gxDict.avp_online, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "MBSFN-Area", gxDict.avp_mbsfn_area, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Extended-APN-AMBR-UL", gxDict.avp_extended_apn_ambr_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Extended-GBR-UL", gxDict.avp_extended_gbr_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Content-Version", gxDict.avp_content_version, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Usage-Monitoring-Report", gxDict.avp_usage_monitoring_report, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Event-Report-Indication", gxDict.avp_event_report_indication, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Job-Type", gxDict.avp_job_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Bearer-Operation", gxDict.avp_bearer_operation, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "User-Equipment-Info-Type", gxDict.avp_user_equipment_info_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TDF-Information", gxDict.avp_tdf_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Request-Number", gxDict.avp_cc_request_number, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Framed-IPv6-Prefix", gxDict.avp_framed_ipv6_prefix, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Packet-Filter-Operation", gxDict.avp_packet_filter_operation, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "CoA-IP-Address", gxDict.avp_coa_ip_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-Charging-Characteristics", gxDict.avp_3gpp_charging_characteristics, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Proxy-Info", gxDict.avp_proxy_info, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Used-Service-Unit", gxDict.avp_used_service_unit, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Rule-Install", gxDict.avp_charging_rule_install, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "MDT-Allowed-PLMN-Id", gxDict.avp_mdt_allowed_plmn_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Origin-Realm", gxDict.avp_origin_realm, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TWAN-Identifier", gxDict.avp_twan_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Rule-Definition", gxDict.avp_charging_rule_definition, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Flow-Label", gxDict.avp_flow_label, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-GGSN-Ipv6-Address", gxDict.avp_3gpp_ggsn_ipv6_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Guaranteed-Bitrate-DL", gxDict.avp_guaranteed_bitrate_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Restriction-Filter-Rule", gxDict.avp_restriction_filter_rule, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-SGSN-Address", gxDict.avp_3gpp_sgsn_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Redirect-Address-Type", gxDict.avp_redirect_address_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TDF-Destination-Realm", gxDict.avp_tdf_destination_realm, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "User-Location-Info-Time", gxDict.avp_user_location_info_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Subscription-Id-Data", gxDict.avp_subscription_id_data, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Redirect-Server-Address", gxDict.avp_redirect_server_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "NBIFOM-Mode", gxDict.avp_nbifom_mode, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Final-Unit-Indication", gxDict.avp_final_unit_indication, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-SGSN-Ipv6-Address", gxDict.avp_3gpp_sgsn_ipv6_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP2-BSID", gxDict.avp_3gpp2_bsid, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Trace-Collection-Entity", gxDict.avp_trace_collection_entity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Session-Release-Cause", gxDict.avp_session_release_cause, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "RAN-Rule-Support", gxDict.avp_ran_rule_support, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Unit-Value", gxDict.avp_unit_value, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Rule-Base-Name", gxDict.avp_charging_rule_base_name, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Report-Interval", gxDict.avp_report_interval, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Presence-Reporting-Area-Node", gxDict.avp_presence_reporting_area_node, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "User-Equipment-Info-Value", gxDict.avp_user_equipment_info_value, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Route-Record", gxDict.avp_route_record, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Presence-Reporting-Area-Identifier", gxDict.avp_presence_reporting_area_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "CSG-Information-Reporting", gxDict.avp_csg_information_reporting, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Filter-Id", gxDict.avp_filter_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Presence-Reporting-Area-Information", gxDict.avp_presence_reporting_area_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "AN-GW-Status", gxDict.avp_an_gw_status, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "SSID", gxDict.avp_ssid, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Metering-Method", gxDict.avp_metering_method, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Flow-Description", gxDict.avp_flow_description, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Logging-Duration", gxDict.avp_logging_duration, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "APN-Aggregate-Max-Bitrate-DL", gxDict.avp_apn_aggregate_max_bitrate_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Conditional-APN-Aggregate-Max-Bitrate", gxDict.avp_conditional_apn_aggregate_max_bitrate, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Access-Network-Charging-Identifier-Gx", gxDict.avp_access_network_charging_identifier_gx, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Positioning-Method", gxDict.avp_positioning_method, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "OC-OLR", gxDict.avp_oc_olr, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Rule-Install", gxDict.avp_routing_rule_install, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Presence-Reporting-Area-Status", gxDict.avp_presence_reporting_area_status, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Trace-Data", gxDict.avp_trace_data, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "SourceID", gxDict.avp_sourceid, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Carrier-Frequency", gxDict.avp_carrier_frequency, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "MBSFN-Area-ID", gxDict.avp_mbsfn_area_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Subscription-Id-Type", gxDict.avp_subscription_id_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Usage-Monitoring-Level", gxDict.avp_usage_monitoring_level, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Bearer-Identifier", gxDict.avp_bearer_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Sponsor-Identity", gxDict.avp_sponsor_identity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "OC-Reduction-Percentage", gxDict.avp_oc_reduction_percentage, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Default-QoS-Name", gxDict.avp_default_qos_name, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Rule-Definition", gxDict.avp_routing_rule_definition, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Traffic-Steering-Policy-Identifier-UL", gxDict.avp_traffic_steering_policy_identifier_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "MDT-Configuration", gxDict.avp_mdt_configuration, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Error-Reporting-Host", gxDict.avp_error_reporting_host, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Rule-Remove", gxDict.avp_charging_rule_remove, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Correlation-Indicator", gxDict.avp_charging_correlation_indicator, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "NBIFOM-Support", gxDict.avp_nbifom_support, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Max-PLR-DL", gxDict.avp_max_plr_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Event-Threshold-Event-1I", gxDict.avp_event_threshold_event_1i, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Rating-Group", gxDict.avp_rating_group, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "RAT-Type", gxDict.avp_rat_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Event-Charging-TimeStamp", gxDict.avp_event_charging_timestamp, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Default-Access", gxDict.avp_default_access, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Event-Threshold-Event-1F", gxDict.avp_event_threshold_event_1f, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Reporting-Level", gxDict.avp_reporting_level, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Allocation-Retention-Priority", gxDict.avp_allocation_retention_priority, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Bearer-Control-Mode", gxDict.avp_bearer_control_mode, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Cell-Global-Identity", gxDict.avp_cell_global_identity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Max-PLR-UL", gxDict.avp_max_plr_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "OC-Validity-Duration", gxDict.avp_oc_validity_duration, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Application-Service-Provider-Identity", gxDict.avp_application_service_provider_identity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "CSG-Membership-Indication", gxDict.avp_csg_membership_indication, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Flow-Direction", gxDict.avp_flow_direction, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Sharing-Key-DL", gxDict.avp_sharing_key_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Default-EPS-Bearer-QoS", gxDict.avp_default_eps_bearer_qos, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Trace-NE-Type-List", gxDict.avp_trace_ne_type_list, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Extended-Max-Requested-BW-DL", gxDict.avp_extended_max_requested_bw_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Redirect-Host", gxDict.avp_redirect_host, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Measurement-Period-LTE", gxDict.avp_measurement_period_lte, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Rule-Report", gxDict.avp_routing_rule_report, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Max-Requested-Bandwidth-DL", gxDict.avp_max_requested_bandwidth_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "User-Equipment-Info", gxDict.avp_user_equipment_info, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Quota-Consumption-Time", gxDict.avp_quota_consumption_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Origin-State-Id", gxDict.avp_origin_state_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "QoS-Negotiation", gxDict.avp_qos_negotiation, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Output-Octets", gxDict.avp_cc_output_octets, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "RAN-NAS-Release-Cause", gxDict.avp_ran_nas_release_cause, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Sharing-Key-UL", gxDict.avp_sharing_key_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "NetLoc-Access-Support", gxDict.avp_netloc_access_support, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Trace-Event-List", gxDict.avp_trace_event_list, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Supported-Features", gxDict.avp_supported_features, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-User-Location-Info", gxDict.avp_3gpp_user_location_info, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Value-Digits", gxDict.avp_value_digits, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Security-Parameter-Index", gxDict.avp_security_parameter_index, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Result-Code", gxDict.avp_result_code, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Trace-Interface-List", gxDict.avp_trace_interface_list, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Fixed-User-Location-Info", gxDict.avp_fixed_user_location_info, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Default-QoS-Information", gxDict.avp_default_qos_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Traffic-Steering-Policy-Identifier-DL", gxDict.avp_traffic_steering_policy_identifier_dl, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Redirect-Max-Cache-Time", gxDict.avp_redirect_max_cache_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Rule-Activation-Time", gxDict.avp_rule_activation_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Load", gxDict.avp_load, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-GGSN-Address", gxDict.avp_3gpp_ggsn_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Redirect-Server", gxDict.avp_redirect_server, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "AN-Trusted", gxDict.avp_an_trusted, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "E-UTRAN-Cell-Global-Identity", gxDict.avp_e_utran_cell_global_identity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Called-Station-Id", gxDict.avp_called_station_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "CSG-Id", gxDict.avp_csg_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Framed-IP-Address", gxDict.avp_framed_ip_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "OC-Supported-Features", gxDict.avp_oc_supported_features, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Packet-Filter-Identifier", gxDict.avp_packet_filter_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "PCC-Rule-Status", gxDict.avp_pcc_rule_status, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TDF-Application-Instance-Identifier", gxDict.avp_tdf_application_instance_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Proxy-Host", gxDict.avp_proxy_host, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Event-Threshold-RSRP", gxDict.avp_event_threshold_rsrp, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Event-Threshold-RSRQ", gxDict.avp_event_threshold_rsrq, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Packet-Filter-Information", gxDict.avp_packet_filter_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Subscription-Id", gxDict.avp_subscription_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Experimental-Result-Code", gxDict.avp_experimental_result_code, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Collection-Period-RRM-LTE", gxDict.avp_collection_period_rrm_lte, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "PDN-Connection-ID", gxDict.avp_pdn_connection_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Access-Network-Charging-Address", gxDict.avp_access_network_charging_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Auth-Application-Id", gxDict.avp_auth_application_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Revalidation-Time", gxDict.avp_revalidation_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Execution-Time", gxDict.avp_execution_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Event-Trigger", gxDict.avp_event_trigger, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Extended-Max-Requested-BW-UL", gxDict.avp_extended_max_requested_bw_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Presence-Reporting-Area-Elements-List", gxDict.avp_presence_reporting_area_elements_list, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Information", gxDict.avp_charging_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Monitoring-Key", gxDict.avp_monitoring_key, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "3GPP-MS-TimeZone", gxDict.avp_3gpp_ms_timezone, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Rule-Name", gxDict.avp_charging_rule_name, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Access-Availability-Change-Reason", gxDict.avp_access_availability_change_reason, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Dynamic-Address-Flag", gxDict.avp_dynamic_address_flag, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Monitoring-Flags", gxDict.avp_monitoring_flags, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Collection-Period-RRM-UMTS", gxDict.avp_collection_period_rrm_umts, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Usage-Monitoring-Information", gxDict.avp_usage_monitoring_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Charging-Rule-Report", gxDict.avp_charging_rule_report, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "IP-CAN-Type", gxDict.avp_ip_can_type, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Offline", gxDict.avp_offline, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "UDP-Source-Port", gxDict.avp_udp_source_port, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-IP-Address", gxDict.avp_routing_ip_address, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Redirect-Information", gxDict.avp_redirect_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Mute-Notification", gxDict.avp_mute_notification, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Media-Component-Number", gxDict.avp_media_component_number, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Tariff-Time-Change", gxDict.avp_tariff_time_change, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Error-Message", gxDict.avp_error_message, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Credit-Management-Status", gxDict.avp_credit_management_status, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Required-Access-Info", gxDict.avp_required_access_info, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "IP-CAN-Session-Charging-Scope", gxDict.avp_ip_can_session_charging_scope, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Reporting-Trigger", gxDict.avp_reporting_trigger, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Failed-AVP", gxDict.avp_failed_avp, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Area-Identity", gxDict.avp_routing_area_identity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Rule-Remove", gxDict.avp_routing_rule_remove, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "TFT-Filter", gxDict.avp_tft_filter, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Trace-Reference", gxDict.avp_trace_reference, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Service-Specific-Units", gxDict.avp_cc_service_specific_units, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Time", gxDict.avp_cc_time, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Currency-Code", gxDict.avp_currency_code, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Input-Octets", gxDict.avp_cc_input_octets, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Measurement-Quantity", gxDict.avp_measurement_quantity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Removal-Of-Access", gxDict.avp_removal_of_access, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Filter", gxDict.avp_routing_filter, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Trace-Depth", gxDict.avp_trace_depth, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Proxy-State", gxDict.avp_proxy_state, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Rule-Failure-Code", gxDict.avp_rule_failure_code, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "AF-Charging-Identifier", gxDict.avp_af_charging_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Tunnel-Header-Length", gxDict.avp_tunnel_header_length, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Rule-Failure-Code", gxDict.avp_routing_rule_failure_code, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "CoA-Information", gxDict.avp_coa_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Default-Bearer-Indication", gxDict.avp_default_bearer_indication, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Vendor-Id", gxDict.avp_vendor_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Granted-Service-Unit", gxDict.avp_granted_service_unit, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Max-Requested-Bandwidth-UL", gxDict.avp_max_requested_bandwidth_ul, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "OC-Sequence-Number", gxDict.avp_oc_sequence_number, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Routing-Rule-Identifier", gxDict.avp_routing_rule_identifier, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Redirect-Support", gxDict.avp_redirect_support, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Destination-Realm", gxDict.avp_destination_realm, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Session-Id", gxDict.avp_session_id, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "ToS-Traffic-Class", gxDict.avp_tos_traffic_class, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Origination-Time-Stamp", gxDict.avp_origination_time_stamp, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "BSSID", gxDict.avp_bssid, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Money", gxDict.avp_cc_money, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Application-Detection-Information", gxDict.avp_application_detection_information, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "QoS-Upgrade", gxDict.avp_qos_upgrade, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "Tariff-Change-Usage", gxDict.avp_tariff_change_usage, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Report-Amount", gxDict.avp_report_amount, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Primary-Event-Charging-Function-Name", gxDict.avp_primary_event_charging_function_name, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME, "CC-Total-Octets", gxDict.avp_cc_total_octets, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Measurement-Period-UMTS", gxDict.avp_measurement_period_umts, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Flows", gxDict.avp_flows, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "PS-to-CS-Session-Continuity", gxDict.avp_ps_to_cs_session_continuity, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "Primary-Charging-Collection-Function-Name", gxDict.avp_primary_charging_collection_function_name, rval, goto err);
    FDCHECK_FCT_DICT(DICT_AVP, AVP_BY_NAME_ALL_VENDORS, "User-CSG-Information", gxDict.avp_user_csg_information, rval, goto err);

    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tdf_destination_host, &gxDict.davp_tdf_destination_host, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pre_emption_capability, &gxDict.davp_pre_emption_capability, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_packet_filter_content, &gxDict.davp_packet_filter_content, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_feature_list_id, &gxDict.davp_feature_list_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_resource_release_notification, &gxDict.davp_resource_release_notification, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_service_identifier, &gxDict.davp_service_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_physical_access_id, &gxDict.davp_physical_access_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_csg_access_mode, &gxDict.davp_csg_access_mode, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_henb_local_ip_address, &gxDict.davp_henb_local_ip_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_dynamic_address_flag_extension, &gxDict.davp_dynamic_address_flag_extension, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_apn_aggregate_max_bitrate_ul, &gxDict.davp_apn_aggregate_max_bitrate_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_network_request_support, &gxDict.davp_network_request_support, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_termination_cause, &gxDict.davp_termination_cause, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_exponent, &gxDict.davp_exponent, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_rat_type, &gxDict.davp_3gpp_rat_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_af_signalling_protocol, &gxDict.davp_af_signalling_protocol, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_packet_filter_usage, &gxDict.davp_packet_filter_usage, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_usage_monitoring_support, &gxDict.davp_usage_monitoring_support, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tracking_area_identity, &gxDict.davp_tracking_area_identity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_load_value, &gxDict.davp_load_value, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_feature_list, &gxDict.davp_feature_list, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_omc_id, &gxDict.davp_omc_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_rai, &gxDict.davp_rai, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_oc_report_type, &gxDict.davp_oc_report_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_experimental_result, &gxDict.davp_experimental_result, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_request_type, &gxDict.davp_cc_request_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_service_context_id, &gxDict.davp_service_context_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_secondary_event_charging_function_name, &gxDict.davp_secondary_event_charging_function_name, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pcscf_restoration_indication, &gxDict.davp_pcscf_restoration_indication, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tdf_ip_address, &gxDict.davp_tdf_ip_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_load_type, &gxDict.davp_load_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_extended_gbr_dl, &gxDict.davp_extended_gbr_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_oc_feature_vector, &gxDict.davp_oc_feature_vector, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_origin_host, &gxDict.davp_origin_host, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pra_remove, &gxDict.davp_pra_remove, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_maximum_wait_time, &gxDict.davp_maximum_wait_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_list_of_measurements, &gxDict.davp_list_of_measurements, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_qos_information, &gxDict.davp_qos_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_final_unit_action, &gxDict.davp_final_unit_action, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_conditional_policy_information, &gxDict.davp_conditional_policy_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_drmp, &gxDict.davp_drmp, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pra_install, &gxDict.davp_pra_install, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_logical_access_id, &gxDict.davp_logical_access_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_resource_allocation_notification, &gxDict.davp_resource_allocation_notification, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_rule_deactivation_time, &gxDict.davp_rule_deactivation_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_flow_status, &gxDict.davp_flow_status, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_priority_level, &gxDict.davp_priority_level, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pre_emption_vulnerability, &gxDict.davp_pre_emption_vulnerability, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_bearer_usage, &gxDict.davp_bearer_usage, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_reporting_reason, &gxDict.davp_reporting_reason, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_qos_class_identifier, &gxDict.davp_qos_class_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_sgsn_mcc_mnc, &gxDict.davp_3gpp_sgsn_mcc_mnc, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_area_scope, &gxDict.davp_area_scope, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_re_auth_request_type, &gxDict.davp_re_auth_request_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_precedence, &gxDict.davp_precedence, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_flow_number, &gxDict.davp_flow_number, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pdn_connection_charging_id, &gxDict.davp_pdn_connection_charging_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_ps_data_off_status, &gxDict.davp_3gpp_ps_data_off_status, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_host_usage, &gxDict.davp_redirect_host_usage, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_an_gw_address, &gxDict.davp_an_gw_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tunnel_header_filter, &gxDict.davp_tunnel_header_filter, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_access_network_charging_identifier_value, &gxDict.davp_access_network_charging_identifier_value, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_secondary_charging_collection_function_name, &gxDict.davp_secondary_charging_collection_function_name, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tcp_source_port, &gxDict.davp_tcp_source_port, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_destination_host, &gxDict.davp_destination_host, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_selection_mode, &gxDict.davp_3gpp_selection_mode, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_location_area_identity, &gxDict.davp_location_area_identity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_logging_interval, &gxDict.davp_logging_interval, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_flow_information, &gxDict.davp_flow_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_ue_local_ip_address, &gxDict.davp_ue_local_ip_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_extended_apn_ambr_dl, &gxDict.davp_extended_apn_ambr_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tdf_application_identifier, &gxDict.davp_tdf_application_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tunnel_information, &gxDict.davp_tunnel_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_media_component_status, &gxDict.davp_media_component_status, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tft_packet_filter_information, &gxDict.davp_tft_packet_filter_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_guaranteed_bitrate_ul, &gxDict.davp_guaranteed_bitrate_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_online, &gxDict.davp_online, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_mbsfn_area, &gxDict.davp_mbsfn_area, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_extended_apn_ambr_ul, &gxDict.davp_extended_apn_ambr_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_extended_gbr_ul, &gxDict.davp_extended_gbr_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_content_version, &gxDict.davp_content_version, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_usage_monitoring_report, &gxDict.davp_usage_monitoring_report, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_event_report_indication, &gxDict.davp_event_report_indication, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_job_type, &gxDict.davp_job_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_bearer_operation, &gxDict.davp_bearer_operation, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_user_equipment_info_type, &gxDict.davp_user_equipment_info_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tdf_information, &gxDict.davp_tdf_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_request_number, &gxDict.davp_cc_request_number, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_framed_ipv6_prefix, &gxDict.davp_framed_ipv6_prefix, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_packet_filter_operation, &gxDict.davp_packet_filter_operation, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_coa_ip_address, &gxDict.davp_coa_ip_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_charging_characteristics, &gxDict.davp_3gpp_charging_characteristics, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_proxy_info, &gxDict.davp_proxy_info, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_used_service_unit, &gxDict.davp_used_service_unit, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_rule_install, &gxDict.davp_charging_rule_install, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_mdt_allowed_plmn_id, &gxDict.davp_mdt_allowed_plmn_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_origin_realm, &gxDict.davp_origin_realm, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_twan_identifier, &gxDict.davp_twan_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_rule_definition, &gxDict.davp_charging_rule_definition, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_flow_label, &gxDict.davp_flow_label, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_ggsn_ipv6_address, &gxDict.davp_3gpp_ggsn_ipv6_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_guaranteed_bitrate_dl, &gxDict.davp_guaranteed_bitrate_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_restriction_filter_rule, &gxDict.davp_restriction_filter_rule, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_sgsn_address, &gxDict.davp_3gpp_sgsn_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_address_type, &gxDict.davp_redirect_address_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tdf_destination_realm, &gxDict.davp_tdf_destination_realm, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_user_location_info_time, &gxDict.davp_user_location_info_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_subscription_id_data, &gxDict.davp_subscription_id_data, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_server_address, &gxDict.davp_redirect_server_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_nbifom_mode, &gxDict.davp_nbifom_mode, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_final_unit_indication, &gxDict.davp_final_unit_indication, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_sgsn_ipv6_address, &gxDict.davp_3gpp_sgsn_ipv6_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp2_bsid, &gxDict.davp_3gpp2_bsid, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_trace_collection_entity, &gxDict.davp_trace_collection_entity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_session_release_cause, &gxDict.davp_session_release_cause, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_ran_rule_support, &gxDict.davp_ran_rule_support, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_unit_value, &gxDict.davp_unit_value, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_rule_base_name, &gxDict.davp_charging_rule_base_name, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_report_interval, &gxDict.davp_report_interval, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_presence_reporting_area_node, &gxDict.davp_presence_reporting_area_node, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_user_equipment_info_value, &gxDict.davp_user_equipment_info_value, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_route_record, &gxDict.davp_route_record, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_presence_reporting_area_identifier, &gxDict.davp_presence_reporting_area_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_csg_information_reporting, &gxDict.davp_csg_information_reporting, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_filter_id, &gxDict.davp_filter_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_presence_reporting_area_information, &gxDict.davp_presence_reporting_area_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_an_gw_status, &gxDict.davp_an_gw_status, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_ssid, &gxDict.davp_ssid, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_metering_method, &gxDict.davp_metering_method, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_flow_description, &gxDict.davp_flow_description, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_logging_duration, &gxDict.davp_logging_duration, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_apn_aggregate_max_bitrate_dl, &gxDict.davp_apn_aggregate_max_bitrate_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_conditional_apn_aggregate_max_bitrate, &gxDict.davp_conditional_apn_aggregate_max_bitrate, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_access_network_charging_identifier_gx, &gxDict.davp_access_network_charging_identifier_gx, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_positioning_method, &gxDict.davp_positioning_method, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_oc_olr, &gxDict.davp_oc_olr, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_rule_install, &gxDict.davp_routing_rule_install, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_presence_reporting_area_status, &gxDict.davp_presence_reporting_area_status, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_trace_data, &gxDict.davp_trace_data, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_sourceid, &gxDict.davp_sourceid, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_carrier_frequency, &gxDict.davp_carrier_frequency, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_mbsfn_area_id, &gxDict.davp_mbsfn_area_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_subscription_id_type, &gxDict.davp_subscription_id_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_usage_monitoring_level, &gxDict.davp_usage_monitoring_level, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_bearer_identifier, &gxDict.davp_bearer_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_sponsor_identity, &gxDict.davp_sponsor_identity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_oc_reduction_percentage, &gxDict.davp_oc_reduction_percentage, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_default_qos_name, &gxDict.davp_default_qos_name, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_rule_definition, &gxDict.davp_routing_rule_definition, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_traffic_steering_policy_identifier_ul, &gxDict.davp_traffic_steering_policy_identifier_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_mdt_configuration, &gxDict.davp_mdt_configuration, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_error_reporting_host, &gxDict.davp_error_reporting_host, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_rule_remove, &gxDict.davp_charging_rule_remove, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_correlation_indicator, &gxDict.davp_charging_correlation_indicator, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_nbifom_support, &gxDict.davp_nbifom_support, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_max_plr_dl, &gxDict.davp_max_plr_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_event_threshold_event_1i, &gxDict.davp_event_threshold_event_1i, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_rating_group, &gxDict.davp_rating_group, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_rat_type, &gxDict.davp_rat_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_event_charging_timestamp, &gxDict.davp_event_charging_timestamp, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_default_access, &gxDict.davp_default_access, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_event_threshold_event_1f, &gxDict.davp_event_threshold_event_1f, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_reporting_level, &gxDict.davp_reporting_level, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_allocation_retention_priority, &gxDict.davp_allocation_retention_priority, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_bearer_control_mode, &gxDict.davp_bearer_control_mode, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cell_global_identity, &gxDict.davp_cell_global_identity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_max_plr_ul, &gxDict.davp_max_plr_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_oc_validity_duration, &gxDict.davp_oc_validity_duration, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_application_service_provider_identity, &gxDict.davp_application_service_provider_identity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_csg_membership_indication, &gxDict.davp_csg_membership_indication, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_flow_direction, &gxDict.davp_flow_direction, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_sharing_key_dl, &gxDict.davp_sharing_key_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_default_eps_bearer_qos, &gxDict.davp_default_eps_bearer_qos, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_trace_ne_type_list, &gxDict.davp_trace_ne_type_list, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_extended_max_requested_bw_dl, &gxDict.davp_extended_max_requested_bw_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_host, &gxDict.davp_redirect_host, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_measurement_period_lte, &gxDict.davp_measurement_period_lte, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_rule_report, &gxDict.davp_routing_rule_report, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_max_requested_bandwidth_dl, &gxDict.davp_max_requested_bandwidth_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_user_equipment_info, &gxDict.davp_user_equipment_info, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_quota_consumption_time, &gxDict.davp_quota_consumption_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_origin_state_id, &gxDict.davp_origin_state_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_qos_negotiation, &gxDict.davp_qos_negotiation, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_output_octets, &gxDict.davp_cc_output_octets, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_ran_nas_release_cause, &gxDict.davp_ran_nas_release_cause, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_sharing_key_ul, &gxDict.davp_sharing_key_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_netloc_access_support, &gxDict.davp_netloc_access_support, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_trace_event_list, &gxDict.davp_trace_event_list, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_supported_features, &gxDict.davp_supported_features, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_user_location_info, &gxDict.davp_3gpp_user_location_info, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_value_digits, &gxDict.davp_value_digits, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_security_parameter_index, &gxDict.davp_security_parameter_index, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_result_code, &gxDict.davp_result_code, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_trace_interface_list, &gxDict.davp_trace_interface_list, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_fixed_user_location_info, &gxDict.davp_fixed_user_location_info, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_default_qos_information, &gxDict.davp_default_qos_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_traffic_steering_policy_identifier_dl, &gxDict.davp_traffic_steering_policy_identifier_dl, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_max_cache_time, &gxDict.davp_redirect_max_cache_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_rule_activation_time, &gxDict.davp_rule_activation_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_load, &gxDict.davp_load, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_ggsn_address, &gxDict.davp_3gpp_ggsn_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_server, &gxDict.davp_redirect_server, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_an_trusted, &gxDict.davp_an_trusted, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_e_utran_cell_global_identity, &gxDict.davp_e_utran_cell_global_identity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_called_station_id, &gxDict.davp_called_station_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_csg_id, &gxDict.davp_csg_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_framed_ip_address, &gxDict.davp_framed_ip_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_oc_supported_features, &gxDict.davp_oc_supported_features, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_packet_filter_identifier, &gxDict.davp_packet_filter_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pcc_rule_status, &gxDict.davp_pcc_rule_status, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tdf_application_instance_identifier, &gxDict.davp_tdf_application_instance_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_proxy_host, &gxDict.davp_proxy_host, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_event_threshold_rsrp, &gxDict.davp_event_threshold_rsrp, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_event_threshold_rsrq, &gxDict.davp_event_threshold_rsrq, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_packet_filter_information, &gxDict.davp_packet_filter_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_subscription_id, &gxDict.davp_subscription_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_experimental_result_code, &gxDict.davp_experimental_result_code, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_collection_period_rrm_lte, &gxDict.davp_collection_period_rrm_lte, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_pdn_connection_id, &gxDict.davp_pdn_connection_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_access_network_charging_address, &gxDict.davp_access_network_charging_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_auth_application_id, &gxDict.davp_auth_application_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_revalidation_time, &gxDict.davp_revalidation_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_execution_time, &gxDict.davp_execution_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_event_trigger, &gxDict.davp_event_trigger, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_extended_max_requested_bw_ul, &gxDict.davp_extended_max_requested_bw_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_presence_reporting_area_elements_list, &gxDict.davp_presence_reporting_area_elements_list, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_information, &gxDict.davp_charging_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_monitoring_key, &gxDict.davp_monitoring_key, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_3gpp_ms_timezone, &gxDict.davp_3gpp_ms_timezone, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_rule_name, &gxDict.davp_charging_rule_name, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_access_availability_change_reason, &gxDict.davp_access_availability_change_reason, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_dynamic_address_flag, &gxDict.davp_dynamic_address_flag, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_monitoring_flags, &gxDict.davp_monitoring_flags, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_collection_period_rrm_umts, &gxDict.davp_collection_period_rrm_umts, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_usage_monitoring_information, &gxDict.davp_usage_monitoring_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_charging_rule_report, &gxDict.davp_charging_rule_report, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_ip_can_type, &gxDict.davp_ip_can_type, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_offline, &gxDict.davp_offline, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_udp_source_port, &gxDict.davp_udp_source_port, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_ip_address, &gxDict.davp_routing_ip_address, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_information, &gxDict.davp_redirect_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_mute_notification, &gxDict.davp_mute_notification, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_media_component_number, &gxDict.davp_media_component_number, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tariff_time_change, &gxDict.davp_tariff_time_change, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_error_message, &gxDict.davp_error_message, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_credit_management_status, &gxDict.davp_credit_management_status, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_required_access_info, &gxDict.davp_required_access_info, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_ip_can_session_charging_scope, &gxDict.davp_ip_can_session_charging_scope, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_reporting_trigger, &gxDict.davp_reporting_trigger, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_failed_avp, &gxDict.davp_failed_avp, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_area_identity, &gxDict.davp_routing_area_identity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_rule_remove, &gxDict.davp_routing_rule_remove, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tft_filter, &gxDict.davp_tft_filter, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_trace_reference, &gxDict.davp_trace_reference, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_service_specific_units, &gxDict.davp_cc_service_specific_units, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_time, &gxDict.davp_cc_time, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_currency_code, &gxDict.davp_currency_code, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_input_octets, &gxDict.davp_cc_input_octets, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_measurement_quantity, &gxDict.davp_measurement_quantity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_removal_of_access, &gxDict.davp_removal_of_access, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_filter, &gxDict.davp_routing_filter, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_trace_depth, &gxDict.davp_trace_depth, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_proxy_state, &gxDict.davp_proxy_state, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_rule_failure_code, &gxDict.davp_rule_failure_code, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_af_charging_identifier, &gxDict.davp_af_charging_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tunnel_header_length, &gxDict.davp_tunnel_header_length, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_rule_failure_code, &gxDict.davp_routing_rule_failure_code, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_coa_information, &gxDict.davp_coa_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_default_bearer_indication, &gxDict.davp_default_bearer_indication, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_vendor_id, &gxDict.davp_vendor_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_granted_service_unit, &gxDict.davp_granted_service_unit, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_max_requested_bandwidth_ul, &gxDict.davp_max_requested_bandwidth_ul, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_oc_sequence_number, &gxDict.davp_oc_sequence_number, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_routing_rule_identifier, &gxDict.davp_routing_rule_identifier, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_redirect_support, &gxDict.davp_redirect_support, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_destination_realm, &gxDict.davp_destination_realm, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_session_id, &gxDict.davp_session_id, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tos_traffic_class, &gxDict.davp_tos_traffic_class, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_origination_time_stamp, &gxDict.davp_origination_time_stamp, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_bssid, &gxDict.davp_bssid, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_money, &gxDict.davp_cc_money, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_application_detection_information, &gxDict.davp_application_detection_information, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_qos_upgrade, &gxDict.davp_qos_upgrade, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_tariff_change_usage, &gxDict.davp_tariff_change_usage, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_report_amount, &gxDict.davp_report_amount, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_primary_event_charging_function_name, &gxDict.davp_primary_event_charging_function_name, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_cc_total_octets, &gxDict.davp_cc_total_octets, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_measurement_period_umts, &gxDict.davp_measurement_period_umts, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_flows, &gxDict.davp_flows, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_ps_to_cs_session_continuity, &gxDict.davp_ps_to_cs_session_continuity, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_primary_charging_collection_function_name, &gxDict.davp_primary_charging_collection_function_name, rval, goto err);
    FDCHECK_FCT_DICT_GETVAL(gxDict.avp_user_csg_information, &gxDict.davp_user_csg_information, rval, goto err);

err:

fini:
    return rval;
}

int gxRegister(void)
{
    int rval = FD_REASON_OK;
    struct disp_when data;

    /* Register the dispatch callbacks */
    memset(&data, 0, sizeof(data));
    data.app = gxDict.appGX;

    FDCHECK_FCT_REGISTER_CALLBACK( gx_rar_cb, gxDict.cmdRAR, rval, goto err);
    /* FDCHECK_FCT_REGISTER_CALLBACK( gx_raa_cb, gxDict.cmdRAA, rval, goto err); */

    FDCHECK_FCT_REGISTER_CALLBACK( gx_cca_cb, gxDict.cmdCCA, rval, goto err);
    /* FDCHECK_FCT_REGISTER_CALLBACK( gx_ccr_cb, gxDict.cmdCCR, rval, goto err); */

    /* Register application support */
    FDCHECK_FCT_REGISTER_APPLICATION( gxDict.appGX, gxDict.vnd3GPP, rval, goto err);

err:

fini:
    return rval;
}
