#ifndef  __GX_DEF_H__
#define  __GX_DEF_H__

#define GX_TDF_DESTINATION_HOST_LEN                          255
#define GX_PACKET_FILTER_CONTENT_LEN                         255
#define GX_PHYSICAL_ACCESS_ID_LEN                            255
#define GX_3GPP_RAT_TYPE_LEN                                 255
#define GX_TRACKING_AREA_IDENTITY_LEN                        255
#define GX_OMC_ID_LEN                                        255
#define GX_RAI_LEN                                           255
#define GX_SECONDARY_EVENT_CHARGING_FUNCTION_NAME_LEN        255
#define GX_ORIGIN_HOST_LEN                                   255
#define GX_LOGICAL_ACCESS_ID_LEN                             255
#define GX_3GPP_SGSN_MCC_MNC_LEN                             255
#define GX_TUNNEL_HEADER_FILTER_LEN                          255
#define GX_ACCESS_NETWORK_CHARGING_IDENTIFIER_VALUE_LEN      255
#define GX_SECONDARY_CHARGING_COLLECTION_FUNCTION_NAME_LEN   255
#define GX_DESTINATION_HOST_LEN                              255
#define GX_3GPP_SELECTION_MODE_LEN                           255
#define GX_LOCATION_AREA_IDENTITY_LEN                        255
#define GX_TDF_APPLICATION_IDENTIFIER_LEN                    255
#define GX_FRAMED_IPV6_PREFIX_LEN                            255
#define GX_3GPP_CHARGING_CHARACTERISTICS_LEN                 255
#define GX_MDT_ALLOWED_PLMN_ID_LEN                           255
#define GX_ORIGIN_REALM_LEN                                  255
#define GX_TWAN_IDENTIFIER_LEN                               255
#define GX_FLOW_LABEL_LEN                                    255
#define GX_3GPP_GGSN_IPV6_ADDRESS_LEN                        255
#define GX_RESTRICTION_FILTER_RULE_LEN                       255
#define GX_3GPP_SGSN_ADDRESS_LEN                             255
#define GX_TDF_DESTINATION_REALM_LEN                         255
#define GX_SUBSCRIPTION_ID_DATA_LEN                          255
#define GX_REDIRECT_SERVER_ADDRESS_LEN                       255
#define GX_3GPP_SGSN_IPV6_ADDRESS_LEN                        255
#define GX_3GPP2_BSID_LEN                                    255
#define GX_CHARGING_RULE_BASE_NAME_LEN                       255
#define GX_USER_EQUIPMENT_INFO_VALUE_LEN                     255
#define GX_ROUTE_RECORD_LEN                                  255
#define GX_PRESENCE_REPORTING_AREA_IDENTIFIER_LEN            255
#define GX_FILTER_ID_LEN                                     255
#define GX_SSID_LEN                                          255
#define GX_FLOW_DESCRIPTION_LEN                              255
#define GX_POSITIONING_METHOD_LEN                            255
#define GX_SOURCEID_LEN                                      255
#define GX_BEARER_IDENTIFIER_LEN                             255
#define GX_SPONSOR_IDENTITY_LEN                              255
#define GX_DEFAULT_QOS_NAME_LEN                              255
#define GX_TRAFFIC_STEERING_POLICY_IDENTIFIER_UL_LEN         255
#define GX_ERROR_REPORTING_HOST_LEN                          255
#define GX_CELL_GLOBAL_IDENTITY_LEN                          255
#define GX_APPLICATION_SERVICE_PROVIDER_IDENTITY_LEN         255
#define GX_TRACE_NE_TYPE_LIST_LEN                            255
#define GX_REDIRECT_HOST_LEN                                 255
#define GX_RAN_NAS_RELEASE_CAUSE_LEN                         255
#define GX_TRACE_EVENT_LIST_LEN                              255
#define GX_3GPP_USER_LOCATION_INFO_LEN                       255
#define GX_SECURITY_PARAMETER_INDEX_LEN                      255
#define GX_TRACE_INTERFACE_LIST_LEN                          255
#define GX_TRAFFIC_STEERING_POLICY_IDENTIFIER_DL_LEN         255
#define GX_3GPP_GGSN_ADDRESS_LEN                             255
#define GX_E_UTRAN_CELL_GLOBAL_IDENTITY_LEN                  255
#define GX_CALLED_STATION_ID_LEN                             255
#define GX_FRAMED_IP_ADDRESS_LEN                             255
#define GX_PACKET_FILTER_IDENTIFIER_LEN                      255
#define GX_TDF_APPLICATION_INSTANCE_IDENTIFIER_LEN           255
#define GX_PROXY_HOST_LEN                                    255
#define GX_PDN_CONNECTION_ID_LEN                             255
#define GX_PRESENCE_REPORTING_AREA_ELEMENTS_LIST_LEN         255
#define GX_MONITORING_KEY_LEN                                255
#define GX_3GPP_MS_TIMEZONE_LEN                              255
#define GX_CHARGING_RULE_NAME_LEN                            255
#define GX_ERROR_MESSAGE_LEN                                 255
#define GX_ROUTING_AREA_IDENTITY_LEN                         255
#define GX_TFT_FILTER_LEN                                    255
#define GX_TRACE_REFERENCE_LEN                               255
#define GX_MEASUREMENT_QUANTITY_LEN                          255
#define GX_PROXY_STATE_LEN                                   255
#define GX_AF_CHARGING_IDENTIFIER_LEN                        255
#define GX_ROUTING_RULE_IDENTIFIER_LEN                       255
#define GX_DESTINATION_REALM_LEN                             255
#define GX_SESSION_ID_LEN                                    255
#define GX_TOS_TRAFFIC_CLASS_LEN                             255
#define GX_BSSID_LEN                                         255
#define GX_PRIMARY_EVENT_CHARGING_FUNCTION_NAME_LEN          255
#define GX_PRIMARY_CHARGING_COLLECTION_FUNCTION_NAME_LEN     255

#endif /* __GX_DEF_H__ */